services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dio
      MONGO_INITDB_ROOT_PASSWORD: dio
    ports:
      - "27017:27017"
    volumes:
      - "C:/Users/Carlos/Desktop/Programação 2024 e Redes/DIO-Java-Bootcamp/dio/Aulas/MongoDB:/data/db"
